FROM python:3.11-slim

WORKDIR /src/aggregator-service

RUN apt-get update && apt-get install build-essential -y curl ca-certificates supervisor && \
    curl -fsSL https://ollama.com/install.sh | sh

RUN pip install fastapi uvicorn requests pandas python-multipart httpx

COPY . .

EXPOSE 11434 8000

CMD sh -c "\
    ollama serve & \
    sleep 5 && \
    ollama pull llama3 && \
    exec uvicorn Main:app --host 0.0.0.0 --port 8000 \
"

