stages:
  - lint
  - build
  - push
  - deploy

include:
  - local: "src/chatroom/.gitlab-ci.yml"
  - local: "src/frontend/.gitlab-ci.yml"

lint:
  stage: lint
  image: python:3.12-slim
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - '**/*.py'
          - '.gitlab-ci.yml'

  before_script:
    - apt-get update && apt-get install -y git
    - pip install ruff
    - git config user.email "ci@gitlab.com"
    - git config user.name "ci-bot"
    - git remote set-url origin https://oauth2:$ACCESS_TOKEN@gitlab.com/${CI_PROJECT_PATH}.git
    - git fetch
    - git checkout $CI_COMMIT_BRANCH

  script:
    - ruff check --extend-select I,W191 --fix .
    - ruff format .
    - |
      if [[ -n $(git status --porcelain) ]]; then
        echo "Changes detected, committing and pushing..."
        git commit -am "ci: ruff lint and format"
        git push origin HEAD:$CI_COMMIT_BRANCH -o ci.skip
      else
        echo "No changes required!"
      fi
