services:
  ollama:
    image: ollama/ollama:latest
    container_name: olalama
    restart: unless-stopped
    privileged: true
    volumes:
      - ${HOME}/.ollama:/root/.ollama:z
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_PARALLEL=3
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    network_mode: host
    command: tunnel run
    env_file: .env
    depends_on:
      - ollama
