# Original Author: Aliaksei Khval
# Source: https://git.chalmers.se/courses/dit826/2025/team2
# License: MIT
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aggregator
  labels:
    app: blundr
    component: aggreagtor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blundr
      component: aggregator
  template:
    metadata:
      labels:
        app: blundr
        component: aggregator
    spec:
      containers:
        - name: aggregator
          image: europe-north2-docker.pkg.dev/blundr/blundr-repo/aggregator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 42069
          env:
            - name: OLLAMA_URL
              value: "https://ollama.max-orlen.com/api/generate"
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  labels:
    app: blundr
    component: aggregator
spec:
  selector:
    app: blundr
    component: aggregator
  ports:
    - name: http
      port: 80
      targetPort: 42069
      protocol: TCP
    - name: legacy
      port: 42069
      targetPort: 42069
      protocol: TCP
  type: ClusterIP
