apiVersion: batch/v1
kind: Job
metadata:
  name: fer-training-job
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: kiddie-pool

      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "training"
          effect: "NoSchedule"

      restartPolicy: Never

      containers:
        - name: test
          image: python:3.9-slim
          command: 
            - "python"
            - "-c"
            - |
              import os, time
              node = os.environ.get('NODE_NAME')
              print(f"running on node {node}")
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
