# Original Author: Aliaksei Khval
# Co-authored by: Maxine Orlen
# Source: https://git.chalmers.se/courses/dit826/2025/team2
# License: MIT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ver
  labels:
    app: blundr
    component: ver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blundr
      component: ver
  template:
    metadata:
      labels:
        app: blundr
        component: ver
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-request: "50m"
    spec:
      serviceAccountName: ver-sa
      terminationGracePeriodSeconds: 600 # avoid terminating background jobs on update
      containers:
        - name: ver
          image: europe-north2-docker.pkg.dev/blundr/blundr-repo/ver:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: gcs-ver-model-bucket
              mountPath: /models
              readOnly: true
          ports:
            - containerPort: 42069
          env:
            - name: AGGREGATOR_URL
              value: "http://aggregator-service.default.svc.cluster.local:42069/aggregator/aggregator"
            - name: MODEL_PATH
              value: "/models/v1/model.pth"
      volumes:
        - name: gcs-ver-model-bucket
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: "blundr-ver-models"
              mountOptions: "implicit-dirs"
---
apiVersion: v1
kind: Service
metadata:
  name: ver-service
  labels:
    app: blundr
    component: ver
spec:
  selector:
    app: blundr
    component: ver
  ports:
    - name: http
      port: 80
      targetPort: 42069
      protocol: TCP
    - name: legacy
      port: 42069
      targetPort: 42069
      protocol: TCP
  type: ClusterIP
