# Original Author: Aliaksei Khval
# Source: https://git.chalmers.se/courses/dit826/2025/team2
# License: MIT
FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements_train.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements_train.txt

COPY ./train/train.py .
COPY ./tests/* .
COPY process_video.py .

EXPOSE 42069

CMD ["python3", "train.py"]
