FROM python:3.12-slim

WORKDIR /app

COPY requirements_train.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements_train.txt

COPY ./train/train.py .
COPY ./tests/* .
COPY process_video.py .

EXPOSE 42069

CMD ["python3", "train.py"]
