services:
  fer-service:
    image: fer
    build: .
    volumes:
      - ./models:/models:ro
    environment:
      - MODEL_PATH=/models/v1/fer_model.pt
    ports:
      - 42069:42069
    profiles:
      - serve

  fer-train:
    image: fer-train
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      # !!! mount actual data and models directories that mimic the GCS setup to test
      - ./test_mounts/models:/models:z
      - ./test_mounts/data:/data:z
    environment:
      - MODEL_VERSION=v2
      - MODEL_BASE_PATH=/models
      - IMAGE_BASE_PATH=/data
    profiles:
      - train
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
