services:
  chatroom:
    build: .
    container_name: chatroom
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "${MEDIASOUP_RTC_MIN_PORT}-${MEDIASOUP_RTC_MAX_PORT}:${MEDIASOUP_RTC_MIN_PORT}-${MEDIASOUP_RTC_MAX_PORT}/udp"
