# Original Author: Razvan Albu
# Source: https://git.chalmers.se/courses/dit826/2025/team2
# License: MIT

services:
  chatroom:
    build: .
    container_name: frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
