services:
  admin-api:
    image: admin-api
    build: .
    volumes:
      - ./models:/models:z
      - ./data:/data:z
      - ${HOME}/.kube/config:/root/.kube/config:ro
    environment:
      - KUBECONFIG=/root/.kube/config
    ports:
      - 42069:42069
